name: test

on: [push]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Dependencies (macOS)
              if: runner.os == 'macOS'
              run: brew install libomp

            - name: Build
              run: make build

            - name: Run tests
              run: make run-tests

            - name: run binaries
              run: |
                  build/source/helloworld
