name: ci

on: [push]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: dependencies (macos)
              if: runner.os == 'macOS'
              run: brew install libomp

            - name: prepare build directory
              run: mkdir build

            - name: generate Makefile
              run: |
                  cd build
                  cmake ..

            - name: build
              run: |
                  cd build
                  make

            - name: run binaries
              run: |
                  build/source/helloworld

            - name: tests
              run: build/source/tests
