name: test

on: [push]

jobs:
    test:
        strategy:
            matrix:
                os: [windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Dependencies (macOS)
              if: runner.os == 'macOS'
              run: brew install clang-format

            - name: Build
              run: make build-windows

            - uses: actions/checkout@v3
            - name: Setup tmate debugging session
              if: ${{ failure() }}
              uses: mxschmitt/action-tmate@v3

            - name: Run Tests
              run: make run-tests

            - name: Run Binaries
              run: |
                  build/source/helloworld

            - name: Lint
              run: make lint
