name: test

on: [push]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Dependencies (macOS)
              if: runner.os == 'macOS'
              run: brew install clang-format

            - name: Build
              run: make build

            - name: Run Tests
              run: make run-tests

            - name: Run Binaries
              run: |
                  build/source/helloworld

            - name: Lint
              run: make lint
